BoxLayout:
    orientation: 'horizontal'
    Button:
        text: "Genesis"


    BoxLayout:
        orientation: 'vertical'

        BoxLayout:
            orientation: 'horizontal'
            Button:
                text: "3"
            Button:
                text: "2"
            Button:
                text: "1"

        BoxLayout:
            orientation: 'vertical'
            Button:
                text: "Genesis"

            Button:
                text: "Text2"
